### ISSUE TITLE
Plan for 0.0.1

### ISSUE THREAD

**Issue by nepalez** [nepalez/rom-cassandra#1]
- [ ] Add `Batch` command
- [ ] Extract `Dataset::DSL` from the overbloated `Dataset`
- [ ] Add `Migrator` (for keyspaces and column families)
- [ ] Read docs
- [ ] Figure out why rbx falls on travis
- [ ] Move all of this to `rom-rb/rom-cassandra`
